export const designTokens = {
  spacing: {
    "0": "var(--ds-space-0)",
    "0.5": "var(--ds-space-0-5)",
    "1": "var(--ds-space-1)",
    "1.5": "var(--ds-space-1-5)",
    "2": "var(--ds-space-2)",
    "2.5": "var(--ds-space-2-5)",
    "3": "var(--ds-space-3)",
    "3.5": "var(--ds-space-3-5)",
    "4": "var(--ds-space-4)",
    "5": "var(--ds-space-5)",
    "6": "var(--ds-space-6)",
    "8": "var(--ds-space-8)",
    "10": "var(--ds-space-10)",
    "12": "var(--ds-space-12)",
    "16": "var(--ds-space-16)",
  },
  typography: {
    sizes: {
      "2xs": "var(--ds-font-size-2xs)",
      xs: "var(--ds-font-size-xs)",
      sm: "var(--ds-font-size-sm)",
      md: "var(--ds-font-size-md)",
      lg: "var(--ds-font-size-lg)",
      xl: "var(--ds-font-size-xl)",
      "2xl": "var(--ds-font-size-2xl)",
      "3xl": "var(--ds-font-size-3xl)",
      "4xl": "var(--ds-font-size-4xl)",
    },
    weights: {
      regular: "var(--ds-font-weight-regular)",
      medium: "var(--ds-font-weight-medium)",
      semibold: "var(--ds-font-weight-semibold)",
      bold: "var(--ds-font-weight-bold)",
    },
  },
  radius: {
    xs: "var(--ds-radius-xs)",
    sm: "var(--ds-radius-sm)",
    md: "var(--ds-radius-md)",
    lg: "var(--ds-radius-lg)",
    xl: "var(--ds-radius-xl)",
    "2xl": "var(--ds-radius-2xl)",
    panel: "var(--ds-radius-panel)",
    full: "var(--ds-radius-full)",
  },
  colors: {
    canvas: "var(--ds-color-canvas)",
    surface: "var(--ds-color-surface)",
    surfaceMuted: "var(--ds-color-surface-muted)",
    surfaceGlass: "var(--ds-color-surface-glass)",
    textPrimary: "var(--ds-color-text-primary)",
    textSecondary: "var(--ds-color-text-secondary)",
    textMuted: "var(--ds-color-text-muted)",
    borderDefault: "var(--ds-color-border-default)",
    borderStrong: "var(--ds-color-border-strong)",
    brandPrimary: "var(--ds-color-brand-primary)",
    brandAccent: "var(--ds-color-brand-accent)",
  },
  elevation: {
    xs: "var(--ds-elevation-xs)",
    sm: "var(--ds-elevation-sm)",
    md: "var(--ds-elevation-md)",
    lg: "var(--ds-elevation-lg)",
    featured: "var(--ds-elevation-featured)",
  },
  motion: {
    fast: "var(--ds-duration-fast)",
    normal: "var(--ds-duration-normal)",
    slow: "var(--ds-duration-slow)",
    loading: "var(--ds-duration-loading)",
    easeStandard: "var(--ds-ease-standard)",
    easeEmphasized: "var(--ds-ease-emphasized)",
  },
} as const;

export type DesignTokens = typeof designTokens;
