import type { Notification } from "@douglas/notifications";

export const notificationSeeds: Notification[] = [
  {
    id: "notification:system-ready",
    type: "success",
    priority: "normal",
    channel: "in_app",
    domain: "system",
    title: "Plataforma pronta",
    message: "Douglas Core e Event Bus corporativo inicializados.",
    status: "unread",
    createdAt: "2026-07-04T12:00:00.000Z",
    metadata: { sourceId: "core" },
  },
  {
    id: "notification:ai-inference",
    type: "info",
    priority: "high",
    channel: "in_app",
    domain: "ai",
    title: "Inferência solicitada",
    message: "Agente Athena preparado para retrieval — simulação arquitetural.",
    status: "unread",
    createdAt: "2026-07-04T12:05:00.000Z",
    metadata: { sourceId: "agent:athena" },
  },
  {
    id: "notification:workflow-complete",
    type: "action",
    priority: "normal",
    channel: "in_app",
    domain: "workflow",
    title: "Workflow concluído",
    message: "Publicação YouTube simulada com sucesso.",
    status: "read",
    createdAt: "2026-07-04T11:30:00.000Z",
    readAt: "2026-07-04T11:35:00.000Z",
    metadata: { sourceId: "workflow:youtube-publish" },
  },
  {
    id: "notification:finance-report",
    type: "info",
    priority: "high",
    channel: "email",
    domain: "financeiro",
    title: "Relatório financeiro",
    message: "Relatório mensal disponível para revisão.",
    status: "unread",
    createdAt: "2026-07-04T10:00:00.000Z",
    metadata: {},
  },
  {
    id: "notification:marketing-campaign",
    type: "warning",
    priority: "normal",
    channel: "in_app",
    domain: "marketing",
    title: "Campanha pendente",
    message: "Aprovação necessária para campanha Q3.",
    status: "unread",
    createdAt: "2026-07-04T09:00:00.000Z",
    metadata: {},
  },
  {
    id: "notification:calma-session",
    type: "success",
    priority: "low",
    channel: "push",
    domain: "calma",
    title: "Sessão Calma iniciada",
    message: "Usuário iniciou jornada de mindfulness.",
    status: "unread",
    createdAt: "2026-07-04T08:00:00.000Z",
    metadata: { sourceId: "session:calma-1" },
  },
  {
    id: "notification:youtube-published",
    type: "success",
    priority: "normal",
    channel: "in_app",
    domain: "youtube",
    title: "Vídeo publicado",
    message: "Upload concluído no YouTube Studio.",
    status: "read",
    createdAt: "2026-07-03T18:00:00.000Z",
    readAt: "2026-07-03T18:05:00.000Z",
    metadata: { sourceId: "video:123" },
  },
  {
    id: "notification:crm-lead",
    type: "action",
    priority: "urgent",
    channel: "in_app",
    domain: "crm",
    title: "Novo lead",
    message: "Lead qualificado aguardando follow-up.",
    status: "unread",
    createdAt: "2026-07-04T07:00:00.000Z",
    metadata: { sourceId: "lead:456" },
  },
];
