import type { AgentDefinition } from "@douglas/agents";

const basePermissions = [
  "read:workspace",
  "read:memory",
  "write:memory",
  "execute:task",
  "emit:events",
] as const;

export const agentDefinitions: AgentDefinition[] = [
  {
    id: "agent:atlas",
    name: "Atlas",
    department: "Inteligência",
    description: "Agente estratégico responsável por visão de longo prazo e priorização.",
    status: "idle",
    priority: "high",
    permissions: [...basePermissions, "manage:tasks"],
    capabilities: ["reasoning", "planning", "analysis"],
    metadata: {
      role: "Estratégia",
      workspaceId: "ws:douglas-os",
      tags: ["strategy", "leadership"],
      inferenceAdapterId: null,
    },
  },
  {
    id: "agent:apollo",
    name: "Apollo",
    department: "Automações",
    description: "Agente operacional para execução de fluxos e automações internas.",
    status: "idle",
    priority: "normal",
    permissions: [...basePermissions],
    capabilities: ["execution", "planning"],
    metadata: {
      role: "Operações",
      workspaceId: "ws:douglas-os",
      tags: ["operations", "automation"],
    },
  },
  {
    id: "agent:aurora",
    name: "Aurora",
    department: "Conteúdo",
    description: "Agente criativo para produção e curadoria de conteúdo.",
    status: "idle",
    priority: "normal",
    permissions: [...basePermissions],
    capabilities: ["communication", "execution"],
    metadata: {
      role: "Conteúdo",
      workspaceId: "ws:douglas-os",
      tags: ["content", "creative"],
    },
  },
  {
    id: "agent:hermes",
    name: "Hermes",
    department: "Marketing",
    description: "Agente de comunicação e relacionamento com stakeholders.",
    status: "idle",
    priority: "normal",
    permissions: [...basePermissions],
    capabilities: ["communication", "reasoning"],
    metadata: {
      role: "Comunicação",
      workspaceId: "ws:douglas-os",
      tags: ["marketing", "communication"],
    },
  },
  {
    id: "agent:athena",
    name: "Athena",
    department: "Pesquisa",
    description: "Agente de pesquisa, retrieval e consolidação de conhecimento.",
    status: "idle",
    priority: "high",
    permissions: [...basePermissions, "invoke:llm"],
    capabilities: ["retrieval", "reasoning", "analysis"],
    metadata: {
      role: "Pesquisa",
      workspaceId: "ws:douglas-os",
      tags: ["research", "knowledge"],
      inferenceAdapterId: "adapter:mock",
    },
  },
  {
    id: "agent:forge",
    name: "Forge",
    department: "Desenvolvimento",
    description: "Agente de construção técnica e implementação de soluções.",
    status: "idle",
    priority: "high",
    permissions: [...basePermissions],
    capabilities: ["execution", "planning", "reasoning"],
    metadata: {
      role: "Construção",
      workspaceId: "ws:douglas-os",
      tags: ["engineering", "build"],
    },
  },
  {
    id: "agent:oracle",
    name: "Oracle",
    department: "Financeiro",
    description: "Agente analítico para métricas, previsões e decisões baseadas em dados.",
    status: "idle",
    priority: "normal",
    permissions: [...basePermissions],
    capabilities: ["analysis", "reasoning"],
    metadata: {
      role: "Análise",
      workspaceId: "ws:douglas-os",
      tags: ["analytics", "finance"],
    },
  },
  {
    id: "agent:nova",
    name: "Nova",
    department: "Vídeo",
    description: "Agente criativo especializado em produção audiovisual.",
    status: "idle",
    priority: "normal",
    permissions: [...basePermissions],
    capabilities: ["execution", "communication"],
    metadata: {
      role: "Criação",
      workspaceId: "ws:douglas-os",
      tags: ["video", "creative"],
    },
  },
];
