import type { MissionData } from "@douglas/missions";

export const missionSeeds: MissionData[] = [
  {
    id: "mission:platform-roadmap",
    title: "Roadmap Q3 da plataforma",
    description: "Consolidar entregas estratégicas do terceiro trimestre.",
    status: "active",
    priority: "critical",
    progress: { percent: 45, completedSteps: 3, totalSteps: 7, currentStep: "Step 4" },
    scopes: [{ type: "project", refId: "project:douglas-os", label: "Douglas AI OS" }],
    execution: { mode: "manual" },
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-04T18:00:00.000Z",
    startedAt: "2026-07-02T09:00:00.000Z",
    metadata: { tags: ["strategy"] },
  },
  {
    id: "mission:athena-research",
    title: "Indexação de conhecimento",
    description: "Agente Athena consolida base de pesquisa.",
    status: "planned",
    priority: "high",
    progress: { percent: 0, completedSteps: 0, totalSteps: 5, currentStep: "Step 1" },
    scopes: [
      { type: "agent", refId: "agent:athena", label: "Athena" },
      { type: "department", refId: "pesquisa", label: "Pesquisa" },
    ],
    execution: {
      mode: "automatic",
      executorId: "agent:athena",
      retryable: true,
      maxRetries: 3,
      scheduledAt: "2026-07-05T08:00:00.000Z",
    },
    createdAt: "2026-07-04T12:00:00.000Z",
    updatedAt: "2026-07-04T12:00:00.000Z",
    metadata: { tags: ["research", "auto"] },
  },
  {
    id: "mission:youtube-publish",
    title: "Publicar vídeo semanal",
    description: "Pipeline YouTube Studio para upload e publicação.",
    status: "active",
    priority: "normal",
    progress: { percent: 70, completedSteps: 7, totalSteps: 10, currentStep: "Step 8" },
    scopes: [
      { type: "product", refId: "youtube-studio", label: "YouTube Studio" },
      { type: "department", refId: "video", label: "Vídeo" },
    ],
    execution: {
      mode: "automatic",
      executorId: "workflow:youtube-publish",
      retryable: true,
      maxRetries: 2,
    },
    createdAt: "2026-07-03T14:00:00.000Z",
    updatedAt: "2026-07-04T17:00:00.000Z",
    startedAt: "2026-07-03T15:00:00.000Z",
    metadata: { tags: ["youtube", "content"] },
  },
  {
    id: "mission:crm-followup",
    title: "Follow-up de leads qualificados",
    description: "Missão comercial independente do pipeline CRM.",
    status: "blocked",
    priority: "high",
    progress: { percent: 20, completedSteps: 1, totalSteps: 5 },
    scopes: [
      { type: "product", refId: "crm", label: "CRM" },
      { type: "agent", refId: "agent:hermes", label: "Hermes" },
    ],
    execution: { mode: "manual" },
    createdAt: "2026-07-04T08:00:00.000Z",
    updatedAt: "2026-07-04T16:00:00.000Z",
    metadata: { tags: ["sales"] },
  },
  {
    id: "mission:finance-report",
    title: "Relatório financeiro mensal",
    description: "Oracle gera relatório independente de outras missões.",
    status: "completed",
    priority: "normal",
    progress: { percent: 100, completedSteps: 4, totalSteps: 4 },
    scopes: [
      { type: "department", refId: "financeiro", label: "Financeiro" },
      { type: "agent", refId: "agent:oracle", label: "Oracle" },
    ],
    execution: { mode: "manual" },
    createdAt: "2026-07-01T09:00:00.000Z",
    updatedAt: "2026-07-04T10:00:00.000Z",
    startedAt: "2026-07-02T09:00:00.000Z",
    completedAt: "2026-07-04T10:00:00.000Z",
    metadata: { tags: ["finance"] },
  },
];
