import type { ChartSeries, Metric, Report } from "@douglas/analytics";

export const analyticsMetricSeeds: Metric[] = [
  {
    id: "metric:calma-sessions",
    key: "sessions_completed",
    label: "Sessões concluídas",
    domain: "calma",
    value: 1284,
    format: "count",
    period: "month",
    previousValue: 1102,
    recordedAt: "2026-07-04T12:00:00.000Z",
    metadata: { sourceId: "calma:app" },
  },
  {
    id: "metric:youtube-views",
    key: "total_views",
    label: "Visualizações totais",
    domain: "youtube",
    value: 45200,
    format: "count",
    period: "month",
    previousValue: 38900,
    recordedAt: "2026-07-04T12:00:00.000Z",
    metadata: { sourceId: "youtube:studio" },
  },
  {
    id: "metric:crm-leads",
    key: "qualified_leads",
    label: "Leads qualificados",
    domain: "crm",
    value: 87,
    format: "count",
    period: "week",
    previousValue: 72,
    recordedAt: "2026-07-04T12:00:00.000Z",
    metadata: {},
  },
  {
    id: "metric:marketing-roi",
    key: "campaign_roi",
    label: "ROI de campanhas",
    domain: "marketing",
    value: 18.4,
    format: "percentage",
    period: "quarter",
    previousValue: 14.2,
    recordedAt: "2026-07-04T12:00:00.000Z",
    metadata: {},
  },
  {
    id: "metric:finance-revenue",
    key: "monthly_revenue",
    label: "Receita mensal",
    domain: "financeiro",
    value: 284500,
    format: "currency",
    period: "month",
    previousValue: 261200,
    recordedAt: "2026-07-04T12:00:00.000Z",
    metadata: {},
  },
  {
    id: "metric:users-active",
    key: "active_users",
    label: "Usuários ativos",
    domain: "usuarios",
    value: 3420,
    format: "count",
    period: "day",
    previousValue: 3180,
    recordedAt: "2026-07-04T12:00:00.000Z",
    metadata: {},
  },
  {
    id: "metric:infra-uptime",
    key: "platform_uptime",
    label: "Uptime da plataforma",
    domain: "infraestrutura",
    value: 99.97,
    format: "percentage",
    period: "month",
    previousValue: 99.92,
    recordedAt: "2026-07-04T12:00:00.000Z",
    metadata: { sourceId: "core:health" },
  },
];

export const analyticsChartSeeds: ChartSeries[] = [
  {
    id: "chart:calma-weekly",
    title: "Sessões Calma — semanal",
    domain: "calma",
    chartType: "bar",
    period: "week",
    updatedAt: "2026-07-04T12:00:00.000Z",
    points: [
      { label: "Seg", value: 142 },
      { label: "Ter", value: 168 },
      { label: "Qua", value: 155 },
      { label: "Qui", value: 190 },
      { label: "Sex", value: 201 },
    ],
  },
  {
    id: "chart:youtube-growth",
    title: "Crescimento YouTube",
    domain: "youtube",
    chartType: "line",
    period: "month",
    updatedAt: "2026-07-04T12:00:00.000Z",
    points: [
      { label: "Jan", value: 12000 },
      { label: "Fev", value: 18500 },
      { label: "Mar", value: 24100 },
      { label: "Abr", value: 31200 },
      { label: "Mai", value: 38900 },
      { label: "Jun", value: 45200 },
    ],
  },
  {
    id: "chart:crm-pipeline",
    title: "Pipeline CRM",
    domain: "crm",
    chartType: "donut",
    period: "week",
    updatedAt: "2026-07-04T12:00:00.000Z",
    points: [
      { label: "Novo", value: 34 },
      { label: "Qualificado", value: 28 },
      { label: "Proposta", value: 15 },
      { label: "Fechado", value: 10 },
    ],
  },
];

export const analyticsReportSeeds: Report[] = [
  {
    id: "report:finance-monthly",
    title: "Relatório Financeiro Mensal",
    domain: "financeiro",
    status: "ready",
    period: "month",
    generatedAt: "2026-07-01T09:00:00.000Z",
    sections: [
      {
        id: "section:revenue",
        title: "Receita",
        summary: "Receita mensal cresceu 8,9% em relação ao mês anterior.",
        metricKeys: ["monthly_revenue"],
      },
      {
        id: "section:costs",
        title: "Custos",
        summary: "Custos operacionais estáveis dentro do orçamento.",
        metricKeys: [],
      },
    ],
  },
  {
    id: "report:marketing-q2",
    title: "Performance Marketing Q2",
    domain: "marketing",
    status: "ready",
    period: "quarter",
    generatedAt: "2026-07-01T09:00:00.000Z",
    sections: [
      {
        id: "section:roi",
        title: "ROI",
        summary: "ROI de campanhas atingiu 18,4%, acima da meta de 15%.",
        metricKeys: ["campaign_roi"],
      },
    ],
  },
  {
    id: "report:infra-health",
    title: "Saúde da Infraestrutura",
    domain: "infraestrutura",
    status: "ready",
    period: "month",
    generatedAt: "2026-07-04T08:00:00.000Z",
    sections: [
      {
        id: "section:uptime",
        title: "Disponibilidade",
        summary: "Uptime de 99,97% — acima do SLA de 99,9%.",
        metricKeys: ["platform_uptime"],
      },
    ],
  },
];
