import type { MemoryRecord } from "@douglas/memory";

export const memorySeedRecords: MemoryRecord[] = [
  {
    id: "memory:platform-mission",
    tier: "long_term",
    domain: "platform",
    kind: "fact",
    content: "Douglas AI Platform é um sistema operacional para produtos e agentes.",
    workspaceId: "ws:douglas-os",
    tags: ["platform", "mission"],
    metadata: { source: "seed" },
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    backendId: "backend:local-core",
  },
  {
    id: "memory:user-preference",
    tier: "long_term",
    domain: "platform",
    kind: "preference",
    content: "Douglas prefere respostas concisas com contexto arquitetural.",
    workspaceId: "ws:douglas-os",
    tags: ["preference", "user"],
    metadata: { source: "seed" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
    backendId: "backend:local-core",
  },
  {
    id: "memory:calma-project",
    tier: "long_term",
    domain: "project",
    kind: "context",
    content: "Calma é a plataforma de bem-estar e mindfulness do portfólio Douglas.",
    workspaceId: "ws:douglas-os",
    projectId: "project:calma",
    tags: ["calma", "project"],
    metadata: { source: "seed" },
    createdAt: "2026-02-01T00:00:00.000Z",
    updatedAt: "2026-02-01T00:00:00.000Z",
    backendId: "backend:local-core",
  },
  {
    id: "memory:athena-agent",
    tier: "long_term",
    domain: "agent",
    kind: "summary",
    content: "Agente Athena especializado em pesquisa e consolidação de conhecimento.",
    workspaceId: "ws:douglas-os",
    agentId: "agent:athena",
    tags: ["agent", "research"],
    metadata: { source: "seed" },
    createdAt: "2026-04-01T00:00:00.000Z",
    updatedAt: "2026-04-01T00:00:00.000Z",
    backendId: "backend:local-core",
  },
  {
    id: "memory:conv-context",
    tier: "short_term",
    domain: "conversation",
    kind: "context",
    content: "Sprint 3.2 focada no Memory Engine oficial, sem IA.",
    workspaceId: "ws:douglas-os",
    conversationId: "conv:platform-review",
    sourceId: "conv:platform-review",
    tags: ["conversation", "session"],
    metadata: { source: "seed" },
    createdAt: "2026-07-04T00:00:00.000Z",
    updatedAt: "2026-07-04T00:00:00.000Z",
    expiresAt: "2026-07-05T00:00:00.000Z",
    backendId: "backend:local-short",
  },
];
